# Generated by Django 5.2.8 on 2025-12-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='t_id',
        ),
    ]
