# Generated by Django 5.2.8 on 2025-12-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_reservation_facility_remove_reservation_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='delete_yn',
            field=models.IntegerField(default=0),
        ),
    ]
