# Generated by Django 5.2.8 on 2025-12-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservation_expire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='expire_date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='expire_yn',
            field=models.IntegerField(default=0),
        ),
    ]
