# Generated by Django 5.2.8 on 2025-12-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='manager_yn',
            field=models.IntegerField(default=0),
        ),
    ]
