# Generated by Django 5.2.8 on 2025-12-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_remove_facilityinfo_sports_facilityinfo_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityinfo',
            name='sido',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facilityinfo',
            name='sigugun',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
