# Generated by Django 5.2.8 on 2025-12-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0004_facilityinfo_sido_facilityinfo_sigugun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityinfo',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='facilityinfo',
            name='sports',
        ),
        migrations.AddField(
            model_name='facilityinfo',
            name='facility_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
