# Generated by Django 5.2.8 on 2025-12-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0006_facilityinfo_view_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='view_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facilityinfo',
            name='rs_posible',
            field=models.IntegerField(default=0),
        ),
    ]
