# Generated by Django 5.2.8 on 2025-12-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0007_facility_view_cnt_facilityinfo_rs_posible'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='faci_gb_nm',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facilityinfo',
            name='faci_gb_nm',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
